[package]
name = "glyph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freetype-rs = "0.28.0"
gl = "0.14.0"
ropey = "1.3.1"
sdl2 = "0.35.1"
