[workspace]
members = [
	"editor",
	"macros",
	"syntax"
]

[patch.crates-io]
tree-sitter = { path = "../deps/tree-sitter/lib", version =  ">= 0.19, < 0.21"}

[patch."https://github.com/tree-sitter/tree-sitter"]
tree-sitter = { path = "../deps/tree-sitter/lib", version =  ">= 0.19, < 0.21"}